### PR TITLE
Automate installation, primarily for e2e setup

### PR DESCRIPTION
**Pull request by solsson**
Supercedes https://github.com/triggermesh/charts/pull/5

The installer concept is idempotent. I've used it quite heavily in e2e, but only on minikube. I've also not had a chance to test the new cloudbuild step, but I can do that after merge.

### CODE REVIEW

**Comment by sebgoa** [comment]
the biggest question with a change like this is: will this affect @cab105 gitlab installs ?

**Comment by solsson** [comment]
I hope that the version bump means that any existing `0.1.2` tarball is unaffected. If we depend on building that 0.1.2 repeatably however we should probably tag the charts repo with v0.1.2 now.

**Comment by cab105** [comment]
We should be okay since I believe the chart version is still published as 0.1.2, however since I'm still in the process of working on my other PR, I'd say lets merge it now and iron out the kinks.

**Comment by solsson** [comment]
Great. I don't have merge access though. I suggest we tag `v0.1.2` prior to merge.

**Comment by solsson** [comment]
@sebgoa Can we tag v0.1.2 and merge this now after today's Gitlab demo?

**Comment by cab105** [comment]
The one question I do have is if this will get pushed to the GCS instance being hosted currently?

**Comment by cab105** [comment]
Okay cool. Did observe that and have updated the work on the other project accordingly. Is there any way to retain the previous versions in case of future version bumps?

**Pull request merged**
